version: '3'

services:
  app-server:
    build: .cloud/docker
    image: laravel-app
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/application:cached

  horizon:
    build: .cloud/docker
    image: laravel-app
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "54306:3306"
    environment:
      - MYSQL_DATABASE=laravel-photo-app
      - MYSQL_ROOT_PASSWORD=secret

    volumes:
      - db-data:/var/lib/mysql:cached

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx:alpine
    ports:
      - "1080:9000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app-server

  redis:
    image: redis:alpine
    ports:
      - "16379:6379"

volumes:
  db-data:
